"""add project_type to expense

Revision ID: 069d3b1994a3
Revises: c9f4a8b2e1d7
Create Date: 2026-06-08 07:04:59.412807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069d3b1994a3'
down_revision = 'c9f4a8b2e1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('project_type')

    # ### end Alembic commands ###
