"""add missing user_id to project tables

Revision ID: 64ce1f757305
Revises: 9aee1f55cb75
Create Date: 2026-03-12 21:41:51.662946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ce1f757305'
down_revision = '9aee1f55cb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_project_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('project_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_project_item_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('project_item_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_project_item_payment_user', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_item_payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_item_payment_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('project_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_item_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_user', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
